# .nvmrc is respected.
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions-using-.nvmrc
language: node_js

cache:
  directories:
    - "node_modules"

# Perform a shallow clone for speed. The default depth is 50.
# https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
git:
  depth: 3

before_install:
  - npm install -g npm@latest
  - npm -v

# TODO: Use serverless to deploy to AWS.
# https://docs.travis-ci.com/user/deployment/script
# deploy:
#   on:
#     branch: master
#   provider: script
#   script: .travis/deploy.sh
#   skip_cleanup: true
