service: courtbot

frameworkVersion: "=1.20.2"

plugins:
  - serverless-secrets-plugin
  - serverless-plugin-warmup
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  environment:
    MIT_RECREATION_PASSWORDS: ${self:custom.secrets.MIT_RECREATION_PASSWORDS}
    MIT_RECREATION_USERNAMES: ${self:custom.secrets.MIT_RECREATION_USERNAMES}
    SLACK_TEAM_ID: ${self:custom.secrets.SLACK_TEAM_ID}
    SLACK_VERIFICATION_TOKEN: ${self:custom.secrets.SLACK_VERIFICATION_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

custom:
  # https://github.com/claygregory/serverless-prune-plugin
  prune:
    automatic: true
    number: 2
  # https://github.com/serverless/serverless-secrets-plugin
  secrets: ${file(secrets.${opt:stage}.yml)}

package:
  # Serverless automatically excludes development dependencies 
  exclude:
    - .eslint*
    - .git/**
    - .gitignore
    - .nvmrc
    - .travis.yml
    - LICENSE
    - package-lock.json
    - package.json
    - README.md
    - secrets.${opt:stage}.yml
    - secrets.${opt:stage}.yml.encrypted
    - serverless.yml

functions:
  router:
    handler: src/index.router
    # https://github.com/FidelLimited/serverless-plugin-warmup
    warmup: true
    events:
      - http:
          method: POST
          path: router
  look:
    handler: src/index.look
  book:
    handler: src/index.book
    timeout: 30
