service: courtbot

# TODO: Upgrade to >=1.20.2
frameworkVersion: "=1.19.0"

plugins:
  - serverless-plugin-warmup
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
  environment:
    # TODO: Use serverless-secrets-plugin
    # https://github.com/serverless/examples/tree/master/aws-node-env-variables-encrypted-in-a-file
    VERIFICATION_TOKEN: ${env:VERIFICATION_TOKEN}
    TEAM_ID: ${env:TEAM_ID}
    MIT_RECREATION_USERNAME: ${env:MIT_RECREATION_USERNAME}
    MIT_RECREATION_PASSWORD: ${env:MIT_RECREATION_PASSWORD}

custom:
  # https://github.com/claygregory/serverless-prune-plugin
  prune:
    automatic: true
    number: 3

functions:
  router:
    handler: handler.router
    # https://github.com/FidelLimited/serverless-plugin-warmup
    warmup: true
    events:
      - http:
          method: POST
          path: router
  look:
    handler: handler.look
  book:
    handler: handler.book
    timeout: 10
