service: courtbot

# TODO: Upgrade to >=1.20.2
frameworkVersion: "=1.19.0"

plugins:
  - serverless-secrets-plugin
  - serverless-plugin-warmup
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

custom:
  # https://github.com/claygregory/serverless-prune-plugin
  prune:
    automatic: true
    number: 3
  # https://github.com/serverless/serverless-secrets-plugin
  secrets: ${file(secrets.${opt:stage}.yml)}

package:
  exclude:
    - secrets.${opt:stage}.yml
    - secrets.${opt:stage}.yml.encrypted

functions:
  router:
    handler: handler.router
    environment:
      SLACK_TEAM_ID: ${self:custom.secrets.SLACK_TEAM_ID}
      SLACK_VERIFICATION_TOKEN: ${self:custom.secrets.SLACK_VERIFICATION_TOKEN}
    # https://github.com/FidelLimited/serverless-plugin-warmup
    warmup: true
    events:
      - http:
          method: POST
          path: router
  look:
    handler: handler.look
  book:
    handler: handler.book
    environment:
      MIT_RECREATION_PASSWORD: ${self:custom.secrets.MIT_RECREATION_PASSWORD}
      MIT_RECREATION_USERNAME: ${self:custom.secrets.MIT_RECREATION_USERNAME}
    timeout: 10
